### ISSUE TITLE
Error parsing a union typedef with an attribute on one type

### ISSUE THREAD

**Issue by Eijebong** [rustwasm/weedle#19] opened 2019-05-12 19:24 UTC
The following line fails to be parsed (it's present in some MediaStream related idl file).

```webidl
typedef ([Clamp] unsigned long or ConstrainULongRange) ConstrainULong;
```

It parses fine it I remove either the attribute on `unsigned long` or remove the `or` part.
Here's the output of the thing parsed without the attribute

```
[Typedef(
    TypedefDefinition {
        attributes: None,
        typedef: Typedef,
        type_: AttributedType {
            attributes: None,
            type_: Union(MayBeNull {
                type_: Braced {
                    open_brace: OpenBrace,
                    body: Punctuated {
                        list: [
                            Single(Integer(MayBeNull { type_: Long(LongType { unsigned: Some(Unsigned), long: Long }), q_mark: None })),
                            Single(Identifier(MayBeNull { type_: Identifier("ConstrainULongRange"), q_mark: None }))
                        ],
                        separator: Or },
                    close_brace: CloseBrace
                }, q_mark: None
            })
        },
        identifier: Identifier("ConstrainULong"), semi_colon: SemiColon
    }
)]
```

I think `MayBeNull` needs an `attributes` field. Does that sound reasonable ?

**Comment by alexcrichton** [comment] 2019-05-13 14:54
Sounds reasonable to me to add!

**Comment by pepsighan** [comment] 2019-05-26 09:35
Looks like the issue is fixed. So closing this.

**Closed as completed by pepsighan** 2019-05-26 09:35 UTC
Labels: bug
